version: "3"
services:
  db:
    image: postgres
    container_name: eduplatform_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    container_name: eduplatform_web
    command: >
      bash -c "python Eduplatform_site/manage.py makemigrations
      && python Eduplatform_site/manage.py migrate
      && python Eduplatform_site/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db