version: "3"
services:
  db:
    image: postgres
    container_name: eduplatform_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
     - .env.dev
    ports:
      - '5432:5432'
    expose:
      - '5432'
  web:
    build: .
    container_name: eduplatform_web
    command: >
      bash -c "python Eduplatform_site/manage.py makemigrations
      && python Eduplatform_site/manage.py migrate
      && python Eduplatform_site/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    env_file:
      - .env.dev
    ports:
      - "8080:8080"
    depends_on:
      - db