# Generated by Django 4.1 on 2022-09-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_create_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-pk'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
