# Generated by Django 4.0.6 on 2022-08-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_create_attempt_model"),
        ("account", "0005_create_group_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.course",
            ),
        ),
    ]
