# Generated by Django 4.0.6 on 2022-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
