# Generated by Django 4.1 on 2022-09-24 20:22

import Eduplatform_site.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_create_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
                ('student', models.ManyToManyField(blank=True, to='learning.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.teacher')),
            ],
            options={
                'verbose_name': 'students_group',
                'verbose_name_plural': 'students_groups',
            },
            bases=(models.Model, Eduplatform_site.mixins.DateTimeMixinModel),
        ),
    ]
