# Generated by Django 4.1 on 2022-09-24 20:22

import Eduplatform_site.mixins
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_create_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('numbering', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Min number value!')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
            options={
                'verbose_name': 'course_topic',
                'verbose_name_plural': 'course_topics',
                'ordering': ['numbering'],
            },
            bases=(models.Model, Eduplatform_site.mixins.DateTimeMixinModel),
        ),
    ]
