# Generated by Django 4.1 on 2022-09-24 20:24

import Eduplatform_site.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_create_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.test')),
            ],
            options={
                'verbose_name': 'test_attempt',
                'verbose_name_plural': 'test_attempts',
            },
            bases=(models.Model, Eduplatform_site.mixins.DateTimeMixinModel),
        ),
    ]
